version: '3.8'

services:
  app_turnos:
    build: .  # Usa el Dockerfile que está en la raíz del proyecto
    container_name: app_turnos
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://turnos_med:5432/turnos
      USERNAME: postgres
      PASSWORD: 12345
    restart: always
    depends_on:
      turnos_med:
        condition: service_healthy

  turnos_med:
    image: postgres:16
    container_name: postgres_turnos
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: turnos
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
